# Generated by Django 2.2 on 2019-05-28 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('organization_url', models.URLField(verbose_name='Organization Website')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('cert_img', models.ImageField(upload_to='img/certifications', verbose_name='Certification')),
                ('cert_related', models.CharField(max_length=50, verbose_name='Techonology studied')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Organization', verbose_name='Organizations')),
            ],
            options={
                'verbose_name': 'certification',
                'verbose_name_plural': 'certifications',
            },
        ),
    ]
