# Generated by Django 2.2 on 2019-05-29 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190529_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='organization',
        ),
        migrations.AddField(
            model_name='certification',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Organization', verbose_name='Organization'),
        ),
    ]
