# Generated by Django 2.2 on 2019-06-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('commercial', 'Commercial'), ('personal', 'Personal'), ('volunteer', 'Volunteer'), ('practice', 'Practice')], max_length=50, verbose_name='Type of project'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='technology',
        ),
        migrations.AddField(
            model_name='project',
            name='technology',
            field=models.ManyToManyField(to='core.Learning', verbose_name='Techonology used'),
        ),
    ]
