# Generated by Django 2.2 on 2019-06-17 09:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_project_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning',
            name='skills',
            field=ckeditor.fields.RichTextField(max_length=200, null=True, verbose_name='skills'),
        ),
    ]
